name: Gabriel Kalani
description: Blog de um adolescente meio louco
meta_description: "Blog de um adolescente, meio louco gkal19"

markdown: kramdown
highlighter: pygments
logo: true
paginate: 15
baseurl: /
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'blog url'
author:         'Gabriel Kalani'
