name: Gabriel Kalani
description: Eu sou Gabriel Kalani, o Batman 
meta_description: "Eu sou Gabriel Kalani, o Batman"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: ''
domain_name: 'http://gkal19.github.io/'
google_analytics: 'UA-30503770-1'
gems:
  - jemoji
  - jekyll-paginate
  - jekyll-twitter-plugin

url:            'http://gkal19.github.io/'
author:         'Gabriel Kalani'
author-image: '/assets/images/profile.jpg'

facebook: gkal19
twitter: gkal19
linkedin: gkal19
github: gkal19