name: Gabriel Kalani
description: pensei que eu era o homem-aranha 
meta_description: "Blog de um adolescente, meio louco gkal19"

markdown: kramdown
highlighter: pygments
logo: true
paginate: 15
baseurl: /
domain_name: 'http://gkal19.github.io/'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'blog url'
author:         'Gabriel Kalani'
