name: Gabriel Kalani
description: pensei que eu era o homem-aranha 
meta_description: "Eu sou Gabriel Kalani, o Batman"

markdown: kramdown
highlighter: pygments
logo: true
paginate: 15
baseurl: /
domain_name: 'http://gkal19.github.io/'
google_analytics: 'UA-30503770-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'blog url'
author:         'Gabriel Kalani'
